/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package it.cnr.istc.icv.timeselector.smart;

import java.util.Date;

/**
 *
 * @author Luca
 */
public class SmartTSTester extends javax.swing.JFrame {

    /**
     * Creates new form SmartTSTester
     */
    public SmartTSTester() {
        initComponents();
        this.smartTimeSelector1.setStartRange(new Date(new Date().getTime() - 1000l*60*60*24*2).getTime());
        this.smartTimeSelector1.setEndRange(new Date().getTime());
        this.smartTimeSelector1.initRedZone();
        
        this.droppableSmartTimeSelector1.setStartRange(new Date(new Date().getTime() - 1000l*60*60*24*2).getTime());
        this.droppableSmartTimeSelector1.setEndRange(new Date().getTime());
        this.droppableSmartTimeSelector1.initRedZone();
        this.droppableSmartTimeSelector1.setStartIntervalWord("From");
        this.droppableSmartTimeSelector1.setEndIntervalWord("To");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        smartTimeSelector1 = new it.cnr.istc.icv.timeselector.smart.SmartTimeSelector();
        droppableSmartTimeSelector1 = new it.cnr.istc.icv.timeselector.smart.DroppableSmartTimeSelector();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout smartTimeSelector1Layout = new javax.swing.GroupLayout(smartTimeSelector1);
        smartTimeSelector1.setLayout(smartTimeSelector1Layout);
        smartTimeSelector1Layout.setHorizontalGroup(
            smartTimeSelector1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        smartTimeSelector1Layout.setVerticalGroup(
            smartTimeSelector1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smartTimeSelector1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(droppableSmartTimeSelector1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(smartTimeSelector1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(droppableSmartTimeSelector1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartTSTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartTSTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartTSTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartTSTester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartTSTester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private it.cnr.istc.icv.timeselector.smart.DroppableSmartTimeSelector droppableSmartTimeSelector1;
    private it.cnr.istc.icv.timeselector.smart.SmartTimeSelector smartTimeSelector1;
    // End of variables declaration//GEN-END:variables
}
