/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package it.cnr.istc.icv.timeselector;

import it.cnr.istc.icv.engine.listeners.ZoomListener;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;

/**
 *
 * @author Luca
 */
public class ProDateSelector extends javax.swing.JPanel implements ZoomListener{

    private GregorianCalendar calendar = new GregorianCalendar();
    private String atLabel = "- at -";    
    private Locale currentLocale = Locale.ENGLISH;
    private RANGE_TYPE identifier = RANGE_TYPE.FROM;
    private PropertyChangeSupport pps = new PropertyChangeSupport(this);
    public static final String DATA_CHANGED = "data is changed";
    
    public enum RANGE_TYPE {FROM,TO};
    
    /**
     * Creates new form ProDateSelector
     */
    public ProDateSelector() {
        initComponents();
        calendar.setTime(new Date());
        updateLabels();
    }
    
    public ProDateSelector(Date date) {
        initComponents();
        calendar.setTime(date);
        updateLabels();
    }
    
    public void addPropertySupportListener(PropertyChangeListener p) {
        pps.addPropertyChangeListener(p);
    }
    
    public void removePropertySupportListener(PropertyChangeListener p) {
        pps.removePropertyChangeListener(p);
        
    }

    public RANGE_TYPE getIdentifier() {
        return identifier;
    }

    public void setIdentifier(RANGE_TYPE identifier) {
        this.identifier = identifier;
    }
    
    
    public void setDate(Date date){
        System.out.println("new date : "+date);
        calendar.setTime(date);
        updateLabels();
    }
    
    public final void updateLabels(){
        this.jLabel_YEAR.setText("<html><div align=center>"+calendar.get(Calendar.YEAR)+"</div>");
        this.jLabel_MONTH.setText("<html><div align=center>"+calendar.getDisplayName(Calendar.MONTH, Calendar.SHORT,currentLocale)+"</div>");
        this.jLabel_DAY.setText("<html><div align=center>"+calendar.get(Calendar.DAY_OF_MONTH)+"</div>");
        int hh = calendar.get(Calendar.HOUR_OF_DAY);
        this.jLabel_HOURS.setText("<html><div align=center>"+(hh < 10 ? "0" : "")+hh+"</div>");
        int mm = calendar.get(Calendar.MINUTE);
        this.jLabel_MINUTS.setText("<html><div align=center>"+(mm < 10 ? "0" : "")+mm+"</div>");
        pps.firePropertyChange(DATA_CHANGED, identifier, calendar);
    }

    public GregorianCalendar getCalendar() {
        return calendar;
    }

    public void setCurrentLocale(Locale currentLocale) {
        this.currentLocale = currentLocale;
    }

    public Locale getCurrentLocale() {
        return currentLocale;
    }

    public void setAtLabel(String atLabel) {
        this.atLabel = "- "+atLabel+" -";
        this.jLabel_at.setText(atLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar3 = new javax.swing.JToolBar();
        jToolBar4 = new javax.swing.JToolBar();
        jButton_AddDay = new javax.swing.JButton();
        jLabel_DAY = new javax.swing.JLabel();
        jButton_minusDay = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jToolBar5 = new javax.swing.JToolBar();
        jButton_addMonth = new javax.swing.JButton();
        jLabel_MONTH = new javax.swing.JLabel();
        jButton_minusMonth = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jToolBar6 = new javax.swing.JToolBar();
        jButton_addYear = new javax.swing.JButton();
        jLabel_YEAR = new javax.swing.JLabel();
        jButton_minusYear = new javax.swing.JButton();
        jLabel_at = new javax.swing.JLabel();
        jToolBar7 = new javax.swing.JToolBar();
        jButton_addHour = new javax.swing.JButton();
        jLabel_HOURS = new javax.swing.JLabel();
        jButton_minusHour = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jToolBar8 = new javax.swing.JToolBar();
        jButton_addMinuts = new javax.swing.JButton();
        jLabel_MINUTS = new javax.swing.JLabel();
        jButton_minusMinuts = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jToolBar3.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        jToolBar4.setBorder(null);
        jToolBar4.setFloatable(false);
        jToolBar4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar4.setRollover(true);

        jButton_AddDay.setBackground(new java.awt.Color(255, 255, 255));
        jButton_AddDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_AddDay.setForeground(new java.awt.Color(0, 153, 51));
        jButton_AddDay.setText("<html><div align=center>+</div>");
        jButton_AddDay.setFocusable(false);
        jButton_AddDay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_AddDay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_AddDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddDayActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton_AddDay);

        jLabel_DAY.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_DAY.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_DAY.setForeground(new java.awt.Color(0, 51, 204));
        jLabel_DAY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_DAY.setText("<html><div align=center>20</div>");
        jLabel_DAY.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_DAY.setOpaque(true);
        jToolBar4.add(jLabel_DAY);

        jButton_minusDay.setBackground(new java.awt.Color(255, 255, 255));
        jButton_minusDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_minusDay.setForeground(new java.awt.Color(204, 0, 0));
        jButton_minusDay.setText("<html><div align=center>-</div>");
        jButton_minusDay.setFocusable(false);
        jButton_minusDay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_minusDay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_minusDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minusDayActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton_minusDay);

        jToolBar3.add(jToolBar4);

        jLabel9.setText("/");
        jToolBar3.add(jLabel9);

        jToolBar5.setBorder(null);
        jToolBar5.setFloatable(false);
        jToolBar5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar5.setRollover(true);

        jButton_addMonth.setBackground(new java.awt.Color(255, 255, 255));
        jButton_addMonth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_addMonth.setForeground(new java.awt.Color(0, 153, 51));
        jButton_addMonth.setText("<html><div align=center>+</div>");
        jButton_addMonth.setFocusable(false);
        jButton_addMonth.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_addMonth.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_addMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addMonthActionPerformed(evt);
            }
        });
        jToolBar5.add(jButton_addMonth);

        jLabel_MONTH.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_MONTH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_MONTH.setForeground(new java.awt.Color(0, 51, 204));
        jLabel_MONTH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_MONTH.setText("<html><div align=center>09</div>");
        jLabel_MONTH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_MONTH.setOpaque(true);
        jToolBar5.add(jLabel_MONTH);

        jButton_minusMonth.setBackground(new java.awt.Color(255, 255, 255));
        jButton_minusMonth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_minusMonth.setForeground(new java.awt.Color(204, 0, 0));
        jButton_minusMonth.setText("<html><div align=center>-</div>");
        jButton_minusMonth.setFocusable(false);
        jButton_minusMonth.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_minusMonth.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_minusMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minusMonthActionPerformed(evt);
            }
        });
        jToolBar5.add(jButton_minusMonth);

        jToolBar3.add(jToolBar5);

        jLabel10.setText("/");
        jToolBar3.add(jLabel10);

        jToolBar6.setBorder(null);
        jToolBar6.setFloatable(false);
        jToolBar6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar6.setRollover(true);

        jButton_addYear.setBackground(new java.awt.Color(255, 255, 255));
        jButton_addYear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_addYear.setForeground(new java.awt.Color(0, 153, 51));
        jButton_addYear.setText("<html><div align=center>+</div>");
        jButton_addYear.setFocusable(false);
        jButton_addYear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_addYear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_addYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addYearActionPerformed(evt);
            }
        });
        jToolBar6.add(jButton_addYear);

        jLabel_YEAR.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_YEAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_YEAR.setForeground(new java.awt.Color(0, 51, 204));
        jLabel_YEAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_YEAR.setText("<html><div align=center>2014</div>");
        jLabel_YEAR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_YEAR.setOpaque(true);
        jToolBar6.add(jLabel_YEAR);

        jButton_minusYear.setBackground(new java.awt.Color(255, 255, 255));
        jButton_minusYear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_minusYear.setForeground(new java.awt.Color(204, 0, 0));
        jButton_minusYear.setText("<html><div align=center>-</div>");
        jButton_minusYear.setFocusable(false);
        jButton_minusYear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_minusYear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_minusYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minusYearActionPerformed(evt);
            }
        });
        jToolBar6.add(jButton_minusYear);

        jToolBar3.add(jToolBar6);

        jLabel_at.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_at.setText(" - at - ");
        jToolBar3.add(jLabel_at);

        jToolBar7.setBorder(null);
        jToolBar7.setFloatable(false);
        jToolBar7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar7.setRollover(true);

        jButton_addHour.setBackground(new java.awt.Color(255, 255, 255));
        jButton_addHour.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_addHour.setForeground(new java.awt.Color(0, 153, 51));
        jButton_addHour.setText("<html><div align=center>+</div>");
        jButton_addHour.setFocusable(false);
        jButton_addHour.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_addHour.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_addHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addHourActionPerformed(evt);
            }
        });
        jToolBar7.add(jButton_addHour);

        jLabel_HOURS.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_HOURS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_HOURS.setForeground(new java.awt.Color(0, 51, 204));
        jLabel_HOURS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_HOURS.setText("<html><div align=center>17</div>");
        jLabel_HOURS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_HOURS.setOpaque(true);
        jToolBar7.add(jLabel_HOURS);

        jButton_minusHour.setBackground(new java.awt.Color(255, 255, 255));
        jButton_minusHour.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_minusHour.setForeground(new java.awt.Color(204, 0, 0));
        jButton_minusHour.setText("<html><div align=center>-</div>");
        jButton_minusHour.setFocusable(false);
        jButton_minusHour.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_minusHour.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_minusHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minusHourActionPerformed(evt);
            }
        });
        jToolBar7.add(jButton_minusHour);

        jToolBar3.add(jToolBar7);

        jLabel12.setText(":");
        jToolBar3.add(jLabel12);

        jToolBar8.setBorder(null);
        jToolBar8.setFloatable(false);
        jToolBar8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar8.setRollover(true);

        jButton_addMinuts.setBackground(new java.awt.Color(255, 255, 255));
        jButton_addMinuts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_addMinuts.setForeground(new java.awt.Color(0, 153, 51));
        jButton_addMinuts.setText("<html><div align=center>+</div>");
        jButton_addMinuts.setFocusable(false);
        jButton_addMinuts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_addMinuts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_addMinuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addMinutsActionPerformed(evt);
            }
        });
        jToolBar8.add(jButton_addMinuts);

        jLabel_MINUTS.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_MINUTS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_MINUTS.setForeground(new java.awt.Color(0, 51, 204));
        jLabel_MINUTS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_MINUTS.setText("<html><div align=center>20</div>");
        jLabel_MINUTS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_MINUTS.setOpaque(true);
        jToolBar8.add(jLabel_MINUTS);

        jButton_minusMinuts.setBackground(new java.awt.Color(255, 255, 255));
        jButton_minusMinuts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_minusMinuts.setForeground(new java.awt.Color(204, 0, 0));
        jButton_minusMinuts.setText("<html><div align=center>-</div>");
        jButton_minusMinuts.setFocusable(false);
        jButton_minusMinuts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_minusMinuts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_minusMinuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minusMinutsActionPerformed(evt);
            }
        });
        jToolBar8.add(jButton_minusMinuts);

        jToolBar3.add(jToolBar8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AddDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddDayActionPerformed
        this.calendar.add(Calendar.DAY_OF_MONTH, 1);
        updateLabels();
    }//GEN-LAST:event_jButton_AddDayActionPerformed

    private void jButton_minusDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minusDayActionPerformed
        this.calendar.add(Calendar.DAY_OF_MONTH, -1);
        updateLabels();
    }//GEN-LAST:event_jButton_minusDayActionPerformed

    private void jButton_addMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addMonthActionPerformed
        this.calendar.add(Calendar.MONTH, 1);
        updateLabels();
    }//GEN-LAST:event_jButton_addMonthActionPerformed

    private void jButton_minusMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minusMonthActionPerformed
        this.calendar.add(Calendar.MONTH, -1);
        updateLabels();
    }//GEN-LAST:event_jButton_minusMonthActionPerformed

    private void jButton_addYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addYearActionPerformed
        this.calendar.add(Calendar.YEAR, 1);
        updateLabels();
    }//GEN-LAST:event_jButton_addYearActionPerformed

    private void jButton_minusYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minusYearActionPerformed
        this.calendar.add(Calendar.YEAR, -1);
        updateLabels();
    }//GEN-LAST:event_jButton_minusYearActionPerformed

    private void jButton_addHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addHourActionPerformed
        this.calendar.add(Calendar.HOUR_OF_DAY, 1);
        updateLabels();
    }//GEN-LAST:event_jButton_addHourActionPerformed

    private void jButton_minusHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minusHourActionPerformed
        this.calendar.add(Calendar.HOUR_OF_DAY, -1);
        updateLabels();
    }//GEN-LAST:event_jButton_minusHourActionPerformed

    private void jButton_addMinutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addMinutsActionPerformed
        this.calendar.add(Calendar.MINUTE, 1);
        updateLabels();
    }//GEN-LAST:event_jButton_addMinutsActionPerformed

    private void jButton_minusMinutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minusMinutsActionPerformed
        this.calendar.add(Calendar.MINUTE, -1);
        updateLabels();
    }//GEN-LAST:event_jButton_minusMinutsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddDay;
    private javax.swing.JButton jButton_addHour;
    private javax.swing.JButton jButton_addMinuts;
    private javax.swing.JButton jButton_addMonth;
    private javax.swing.JButton jButton_addYear;
    private javax.swing.JButton jButton_minusDay;
    private javax.swing.JButton jButton_minusHour;
    private javax.swing.JButton jButton_minusMinuts;
    private javax.swing.JButton jButton_minusMonth;
    private javax.swing.JButton jButton_minusYear;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_DAY;
    private javax.swing.JLabel jLabel_HOURS;
    private javax.swing.JLabel jLabel_MINUTS;
    private javax.swing.JLabel jLabel_MONTH;
    private javax.swing.JLabel jLabel_YEAR;
    private javax.swing.JLabel jLabel_at;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JToolBar jToolBar6;
    private javax.swing.JToolBar jToolBar7;
    private javax.swing.JToolBar jToolBar8;
    // End of variables declaration//GEN-END:variables

    @Override
    public void zoomSelected() {
    }

    @Override
    public void zoomResetted() {
    }

    @Override
    public void zoomNewInterval(Date startRange, Date endRange) {
        System.out.println("NEW INTERVAL !!");
        if(this.identifier == RANGE_TYPE.FROM){
            System.out.println("NEW RANGE FROM !!!");
            this.setDate(startRange);
        }else{
            this.setDate(endRange);
        }
    }

}
