/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.cnr.istc.icv.engine;

import java.awt.Color;
import java.awt.GridLayout;
import java.util.Date;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Luca
 */
public class EmbeddablePanel extends javax.swing.JPanel {

    final MixedDataPanel panel = new MixedDataPanel();
    private volatile String zoomLabeledValueWord;
    private volatile String startIntervalWord;
    private volatile String endIntervalWord;
    private MyLayer<JPanel> layerUI;

    public MixedDataPanel getMixedPanel() {
        return panel;
    }

    /**
     * Creates new form DroppableTestPanel
     */
    public EmbeddablePanel() {
        initComponents();
//        ActivityDataPriority.MEDIUM_COLOR_START = Color.MAGENTA;
        panel.setStartRange(new Date(113, 9, 5, 9, 0, 0).getTime());
        panel.setEndRange(new Date(113, 9, 5, 12, 0, 0).getTime());
        panel.setBackground(Color.WHITE);
        panel.setZoomEnable(true);
        layerUI = new ZoomLabeledLayer(panel);
        ((ZoomLabeledLayer)layerUI).setBaseValueWord(zoomLabeledValueWord);
        ((ZoomLabeledLayer)layerUI).setFromTranslated(startIntervalWord);
        ((ZoomLabeledLayer)layerUI).setToTranslated(endIntervalWord);
        JPanel containerP = new JPanel();
        containerP.setLayout(new GridLayout(0, 1));
        containerP.add(panel);

        MyJLayer<JPanel> jlayer = new MyJLayer<JPanel>(panel, layerUI);
        containerP.add(jlayer);
        
        
        this.jScrollPane1.setBorder(null);
        this.jScrollPane1.setViewportView(containerP);
        
        this.setLayout(new GridLayout(0, 1));
        this.add(jScrollPane1);
        this.setOpaque(false);
        
        MyLayer<JComponent> top = new TopHeaderLayer(panel, this.jScrollPane1.getVerticalScrollBar());
        MyJLayer<JComponent> layer2 = new MyJLayer<JComponent>(jScrollPane1, top);
        
        this.add(layer2);
        
        
        
//        this.jScrollPane1.getViewport().add(containerP2);
        
        
        
        
//        MyLayer<JComponent> top = new TopHeaderLayer(panel);
//        MyJLayer<JComponent> layer2 = new MyJLayer<JComponent>(panel, top);
//        this.jScrollPane1.add(layer2);
//        

    }
    
    public void setXTooltipLabel(String xLabel){
        ((ZoomLabeledLayer)layerUI).setxLabel(xLabel);
    }
    
    public void setYTooltipLabel(String yLabel){
        ((ZoomLabeledLayer)layerUI).setyLabel(yLabel);
    }

    public void setStartIntervalWord(String startIntervalWord) {
        this.startIntervalWord = startIntervalWord;
        ((ZoomLabeledLayer)layerUI).setFromTranslated(startIntervalWord);
        
    }

    public void setEndIntervalWord(String endIntervalWord) {
        this.endIntervalWord = endIntervalWord;
        ((ZoomLabeledLayer)layerUI).setToTranslated(endIntervalWord);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JScrollPane getScroller(){
        return this.jScrollPane1;
    }

    public void setZoomLabeledValueWord(String zoomLabeledValueWord) {
        this.zoomLabeledValueWord = zoomLabeledValueWord;
    }

    public String getZoomLabeledValueWord() {
        return zoomLabeledValueWord;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
