/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.cnr.istc.icv.test;

import it.cnr.istc.icv.engine.MixedDataPanel;
import it.cnr.istc.icv.engine.MyJLayer;
import it.cnr.istc.icv.engine.MyLayer;
import it.cnr.istc.icv.engine.ZoomLayer;
import it.cnr.istc.icv.exceptions.TypeDataMismatchException;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JButton;
//import javax.swing.JLayer;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JSplitPane;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
//import javax.swing.plaf.LayerUI;

/**
 *
 * @author Luca
 */
public class TesterFrame2 extends javax.swing.JFrame {

    private MixedDataPanel mixedDataPanel = new MixedDataPanel();

    /**
     * Creates new form TesterFrame2
     */
    public TesterFrame2() {
        initComponents();
        mixedDataPanel.setBackgroundChartColor(Color.WHITE);
        mixedDataPanel.setBackground(Color.WHITE);

        mixedDataPanel.setStartRange(new Date(113, 9, 5, 8, 0, 0).getTime());
        mixedDataPanel.setEndRange(new Date(113, 9, 5, 12, 0, 0).getTime());


//            panel.setyAxisDataColor(Color.yellow);
//            panel.setxAxisDataColor(Color.yellow);
//            panel.set
        //        panel.setDataColor(new Color(0,146,29));
        mixedDataPanel.setZoomEnable(true);
//        mixedDataPanel.setStartRange(new Date().getTime() - 1000 * 60 * 5);
//        mixedDataPanel.setEndRange(new Date().getTime());
        MyLayer<JPanel> layerUI = new ZoomLayer(mixedDataPanel);
        JPanel containerP = new JPanel();
        containerP.setLayout(new GridLayout(0, 1));
        containerP.add(mixedDataPanel);

        MyJLayer<JPanel> jlayer = new MyJLayer<JPanel>(mixedDataPanel, layerUI);
        containerP.add(jlayer);
        this.jSplitPane1.setRightComponent(containerP);


        LinearBooleanDataSupporter b1 = new LinearBooleanDataSupporter("Door Contact");
        BooleanDataSupporter bs1 = new BooleanDataSupporter(new Date(113, 9, 5, 9, 30, 0), true);
        BooleanDataSupporter bs2 = new BooleanDataSupporter(new Date(113, 9, 5, 11, 0, 0), false);
        b1.addData(bs1);
        b1.addData(bs2);
        Map<Boolean, String> bMap = new HashMap<Boolean, String>();
        bMap.put(true, "Aperto e riaperto più e più volte .. ciao come va? ");
//            bMap.put(false, "Chiuso");
        b1.mapValues("Door Contact", bMap);
        mixedDataPanel.addDataBar(b1);
        mixedDataPanel.repaint();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new JProgressBar();
        jSplitPane1 = new JSplitPane();
        jButton_test3 = new JButton();
        jButton_test4 = new JButton();
        jButton_test5 = new JButton();
        jButton_test6 = new JButton();
        jButton_test2 = new JButton();
        jButton_test1 = new JButton();
        jButton1 = new JButton();
        jButton2 = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jButton_test3.setText("3");
        jButton_test3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton_test3ActionPerformed(evt);
            }
        });

        jButton_test4.setText("4");
        jButton_test4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton_test4ActionPerformed(evt);
            }
        });

        jButton_test5.setText("5");
        jButton_test5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton_test5ActionPerformed(evt);
            }
        });

        jButton_test6.setText("6");
        jButton_test6.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton_test6ActionPerformed(evt);
            }
        });

        jButton_test2.setText("2");
        jButton_test2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton_test2ActionPerformed(evt);
            }
        });

        jButton_test1.setText("1");
        jButton_test1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton_test1ActionPerformed(evt);
            }
        });

        jButton1.setText("IMP");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("A1");
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_test1, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jButton_test2, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_test3, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_test4, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_test5, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_test6, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_test2, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton_test1, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton_test6, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton_test5, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton_test4, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton_test3, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_test3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton_test3ActionPerformed
        mixedDataPanel.clear();
        LinearBooleanDataSupporter b1 = new LinearBooleanDataSupporter("TEST 3");
        BooleanDataSupporter bs1 = new BooleanDataSupporter(new Date(113, 9, 5, 10, 0, 0), false);
        BooleanDataSupporter bs3 = new BooleanDataSupporter(new Date(113, 9, 5, 11, 0, 0), true);
        b1.addData(bs1);
        b1.addData(bs3);
        Map<Boolean, String> bMap = new HashMap<Boolean, String>();
        bMap.put(true, "Aperto");
        bMap.put(false, "Chiuso");
        b1.mapValues("TEST 3", bMap);
        mixedDataPanel.addDataBar(b1);
        mixedDataPanel.repaint();
    }//GEN-LAST:event_jButton_test3ActionPerformed

    private void jButton_test1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton_test1ActionPerformed

        mixedDataPanel.clear();
        LinearBooleanDataSupporter b1 = new LinearBooleanDataSupporter("TEST 1");
        BooleanDataSupporter bs1 = new BooleanDataSupporter(new Date(113, 9, 5, 10, 0, 0), true);
        b1.addData(bs1);
        Map<Boolean, String> bMap = new HashMap<Boolean, String>();
        bMap.put(true, "Aperto");
//            bMap.put(false, "Chiuso");
        b1.mapValues("TEST 1", bMap);
        mixedDataPanel.addDataBar(b1);
        mixedDataPanel.repaint();
    }//GEN-LAST:event_jButton_test1ActionPerformed

    private void jButton_test2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton_test2ActionPerformed
        mixedDataPanel.clear();
        LinearBooleanDataSupporter b1 = new LinearBooleanDataSupporter("TEST 2");
        BooleanDataSupporter bs1 = new BooleanDataSupporter(new Date(113, 9, 5, 10, 0, 0), true);
        BooleanDataSupporter bs2 = new BooleanDataSupporter(new Date(113, 9, 5, 11, 0, 0), false);
        b1.addData(bs1);
        b1.addData(bs2);
        Map<Boolean, String> bMap = new HashMap<Boolean, String>();
        bMap.put(true, "Aperto");
        bMap.put(false, "Chiuso");
        b1.mapValues("TEST 2", bMap);
        mixedDataPanel.addDataBar(b1);
        mixedDataPanel.repaint();
    }//GEN-LAST:event_jButton_test2ActionPerformed

    private void jButton_test4ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton_test4ActionPerformed
        mixedDataPanel.clear();
        LinearBooleanDataSupporter b1 = new LinearBooleanDataSupporter("TEST 4");
        BooleanDataSupporter bs1 = new BooleanDataSupporter(new Date(113, 9, 5, 10, 0, 0), false);

        b1.addData(bs1);

        Map<Boolean, String> bMap = new HashMap<Boolean, String>();
        bMap.put(true, "Aperto");
//            bMap.put(false, "Chiuso");
        b1.mapValues("TEST 4", bMap);
        mixedDataPanel.addDataBar(b1);
        mixedDataPanel.repaint();
    }//GEN-LAST:event_jButton_test4ActionPerformed

    private void jButton_test5ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton_test5ActionPerformed
                mixedDataPanel.clear();
        LinearBooleanDataSupporter b1 = new LinearBooleanDataSupporter("TEST 5");
        BooleanDataSupporter bs1 = new BooleanDataSupporter(new Date(113, 9, 5, 10, 0, 0), false);
        BooleanDataSupporter bs2 = new BooleanDataSupporter(new Date(113, 9, 5, 11, 0, 0), true);
        b1.addData(bs1);
        b1.addData(bs2);
        Map<Boolean, String> bMap = new HashMap<Boolean, String>();
        bMap.put(true, "Aperto");
        bMap.put(false, "Chiuso");
        b1.mapValues("TEST 5", bMap);
        mixedDataPanel.addDataBar(b1);
        mixedDataPanel.repaint();
    }//GEN-LAST:event_jButton_test5ActionPerformed

    private void jButton_test6ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton_test6ActionPerformed
                        mixedDataPanel.clear();
        LinearBooleanDataSupporter b1 = new LinearBooleanDataSupporter("TEST 6");
        BooleanDataSupporter bs1 = new BooleanDataSupporter(new Date(113, 9, 5, 10, 0, 0), false);
        BooleanDataSupporter bs2 = new BooleanDataSupporter(new Date(113, 9, 5, 10, 30, 0), true);
        BooleanDataSupporter bs3 = new BooleanDataSupporter(new Date(113, 9, 5, 11, 0, 0), false);
        b1.addData(bs1);
        b1.addData(bs2);
        b1.addData(bs3);
        Map<Boolean, String> bMap = new HashMap<Boolean, String>();
        bMap.put(true, "Aperto");
        bMap.put(false, "Chiuso");
        b1.mapValues("TEST 6", bMap);
        mixedDataPanel.addDataBar(b1);
        mixedDataPanel.repaint();
    }//GEN-LAST:event_jButton_test6ActionPerformed

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            mixedDataPanel.clear();
            ImpulsiveBooleanDataSupporter b1 = new ImpulsiveBooleanDataSupporter("TEST 7");
            b1.setIdle(1000*60*60);
            BooleanDataSupporter bs1 = new BooleanDataSupporter(new Date(113, 9, 5, 10, 0, 0), true);
            BooleanDataSupporter bs2 = new BooleanDataSupporter(new Date(113, 9, 5, 10, 20, 0), true);
            BooleanDataSupporter bs3 = new BooleanDataSupporter(new Date(113, 9, 5, 11, 30, 0), true);
    //        b1.addData(bs1);
    //        b1.addData(bs2);
    //        b1.addData(bs3);
            Map<Boolean, String> bMap = new HashMap<Boolean, String>();
            bMap.put(true, "Aperto");
            bMap.put(false, "Chiuso");
            b1.mapValues("TEST 7", bMap);
            mixedDataPanel.addDataBar(b1);
            mixedDataPanel.addBooleanData("TEST 7", bs1, true);
            mixedDataPanel.addBooleanData("TEST 7", bs2, true);
            mixedDataPanel.addBooleanData("TEST 7", bs3, true);
            mixedDataPanel.repaint();
        } catch (TypeDataMismatchException ex) {
            Logger.getLogger(TesterFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           try {
            mixedDataPanel.clear();

            ActivityContainerSupporter acs = new ActivityContainerSupporter("A1");
            ActivityContainerSupporter acs2 = new ActivityContainerSupporter("A2");
//            mixedDataPanel.addDataBar(acs);
//            for (ActivityInstance act_data : activityList) {
//                mixedDataPanel1.addActivityData(new ActivityDataSupporter(I18nTranslator.getInstance().translate(activityName), act_data.start, act_data.end), false);
//            }

//            ActivityContainerSupporter a1 = new ActivityContainerSupporter("A1");
            mixedDataPanel.addDataBar(acs);
            mixedDataPanel.addDataBar(acs2);
            ActivityDataSupporter a1Data1 = new ActivityDataSupporter("A1", new Date(113, 9, 5, 10, 0, 0), new Date(113, 9, 5, 10, 20, 0));
            ActivityDataSupporter a1Data2 = new ActivityDataSupporter("A2", new Date(113, 9, 5, 10, 25, 0), new Date(113, 9, 5, 10, 35, 0));
            ActivityDataSupporter a1Data3 = new ActivityDataSupporter("A1", new Date(113, 9, 5, 10, 50, 0), new Date(113, 9, 5, 10, 52, 0));
            ActivityDataSupporter a1Data4 = new ActivityDataSupporter("A1", new Date(113, 9, 5, 11, 0, 0), new Date(113, 9, 5, 11, 20, 0));
            
            mixedDataPanel.addActivityData(a1Data1, false);
            mixedDataPanel.addActivityData(a1Data2, false);
            mixedDataPanel.addActivityData(a1Data3, false);
            mixedDataPanel.addActivityData(a1Data4, true);
            mixedDataPanel.repaint();
        } catch (TypeDataMismatchException ex) {
            Logger.getLogger(TesterFrame2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesterFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesterFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesterFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesterFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesterFrame2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton_test1;
    private JButton jButton_test2;
    private JButton jButton_test3;
    private JButton jButton_test4;
    private JButton jButton_test5;
    private JButton jButton_test6;
    private JProgressBar jProgressBar1;
    private JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
